import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import { notificationProvider, RefineSnackbarProvider } from "@refinedev/mui";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";

import { AppIcon } from "@components/app-icon";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { authProviderClient } from "@providers/auth-provider";
import { dataProvider } from "@providers/data-provider";

import ArrowRight from "@mui/icons-material/ArrowRight";
import Newspaper from "@mui/icons-material/Newspaper";
import Category from "@mui/icons-material/Category";


export const metadata: Metadata = {
  title: "Empreendedor Serial",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  return (
    <html lang="pt">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <ColorModeContextProvider defaultMode={defaultMode}>
              <RefineSnackbarProvider>
                  <Refine
                    routerProvider={routerProvider}
                    authProvider={authProviderClient}
                    dataProvider={dataProvider}
                    //notificationProvider={notificationProvider}
                    resources={[
                      {
                        name: "blog_posts",
                        list: "/admin/blog-posts",
                        create: "/admin/blog-posts/create",
                        edit: "/admin/blog-posts/edit/:id",
                        show: "/admin/blog-posts/show/:id",
                        meta: {
                          canDelete: true,
                          label: "Matérias",
                          icon: <Newspaper />,
                          foo: "categories",

                        },
                      },
                      {
                        name: "categories",
                        list: "/admin/categories",
                        create: "/admin/categories/create",
                        edit: "/admin/categories/edit/:id",
                        show: "/admin/categories/show/:id",
                        meta: {
                          canDelete: true,
                          label: "Categorias",
                          icon: <Category />
                        },
                      },
                      {
                        name: "products",
                        list: "/admin/products",
                        create: "/admin/products/create",
                        edit: "/admin/products/edit/:id",
                        show: "/admin/products/show/:id",
                        meta: {
                          canDelete: true,
                          label: "Products",
                          icon: <Category />
                        },
                      },
                    ]}
                    options={{
                      syncWithLocation: true,
                      warnWhenUnsavedChanges: true,
                      useNewQueryKeys: true,
                      projectId: "IbRHXl-p6FEIM-Z056GV",
                      title: { text: "App Empreendedor Serial", icon: <AppIcon /> },
                    }}
                  >
                    {children}
                    <RefineKbar />
                  </Refine>
              </RefineSnackbarProvider>
            </ColorModeContextProvider>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
